grafana:
  adminPassword: admin

  plugins:
    - alexanderzobnin-zabbix-app

  initContainers:
    - name: install-plugins
      image: busybox:1.31.1
      command:
        - sh
        - -c
        - >
          mkdir -p /var/lib/grafana/plugins/alexanderzobnin-zabbix-app &&
          wget -q https://grafana.com/api/plugins/alexanderzobnin-zabbix-app/versions/latest/download -O /tmp/zabbix.zip &&
          unzip -q /tmp/zabbix.zip -d /var/lib/grafana/plugins/alexanderzobnin-zabbix-app
      volumeMounts:
        - name: grafana-plugins
          mountPath: /var/lib/grafana/plugins

  extraVolumes:
    - name: grafana-plugins
      emptyDir: {}

  extraVolumeMounts:
    - name: grafana-plugins
      mountPath: /var/lib/grafana/plugins

  provisioning:
    datasources:
      - name: Zabbix
        orgId: 1
        type: alexanderzobnin-zabbix-app
        access: proxy
        url: http://zabbix-zabbix-web.observability.svc.cluster.local/api_jsonrpc.php
        isDefault: true
        version: 6
        jsonData:
          trends: true
          cacheTTL: "1m"
          timeout: 30
        secureJsonData:
          username: Admin
          password: zabbix
