apiVersion: v1
kind: ConfigMap
metadata:
  name: menu-service-configmap
data:
  rabbitmq_host: "rabbitmq-service"
  cn_db: "mongodb://user:pass@mongodb-service:27017/FastTechFoods-ProductsDB?authSource=admin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
data:
  zabbix_agentd.conf: |
    Server=0.0.0.0/0
    ServerActive=zabbix-zabbix-server
    Hostname=menu-service-container
    ListenPort=10050
    ListenIP=0.0.0.0
    LogType=console

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service-deployment
  labels:
    app: menu-service
  annotations:
    type: "consumer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: erickgoldberg/fasttechfoods-productservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name:  menu-service-configmap
              key: rabbitmq_host
        - name: MONGO_DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name:  menu-service-configmap
              key: cn_db
      - name: zabbix-agent
        image: zabbix/zabbix-agent:alpine-6.0-latest
        volumeMounts:
        - name: zabbix-agent-config
          mountPath: /etc/zabbix/zabbix_agentd.conf
          subPath: zabbix_agentd.conf
        ports:
        - containerPort: 10050

      volumes: 
      - name: zabbix-agent-config
        configMap:
          name: zabbix-agent-config
---

apiVersion: v1
kind: Service
metadata:
  name: menu-service-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: menu-service


---
apiVersion: v1
kind: Service
metadata:
  name: menu-service-zabbix-agent-service
spec:
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 10050
    targetPort: 10050
  type: ClusterIP
