apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"

    services:
      - name: orderservice-service
        host: orderservice-service
        port: 8080
        protocol: http
        routes:
          - name: orderservice-service
            paths: ["/"]
            protocols:
              - http

    plugins:
      - name: rate-limiting
        config:
          second: 5 
          minute: 10
          hour: 1000
          limit_by: consumer
      - name: prometheus
        config:
          per_consumer: true
          status_code_metrics: true
          latency_metrics: true
          bandwidth_metrics: true
          upstream_health_metrics: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
data:
  zabbix_agentd.conf: |
    Server=0.0.0.0/0
    ServerActive=zabbix-zabbix-server
    Hostname=kong-container
    ListenPort=10050
    ListenIP=0.0.0.0
    LogType=console

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.8
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /etc/kong/kong.yml
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/kong.yml
              subPath: kong.yml
          livenessProbe:
            httpGet:
              path: /status
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-6.0-latest
          volumeMounts:
          - name: zabbix-agent-config
            mountPath: /etc/zabbix/zabbix_agentd.conf
            subPath: zabbix_agentd.conf
          ports:
          - containerPort: 10050
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
        - name: zabbix-agent-config
          configMap:
            name: zabbix-agent-config
---

apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 32000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 32001
    - name: admin-ssl
      port: 8444
      targetPort: 8444
  selector:
    app: kong


---

apiVersion: v1
kind: Service
metadata:
  name: kong-zabbix-agent-service
spec:
  selector:
    app: kong
  ports:
  - protocol: TCP
    port: 10050
    targetPort: 10050
  type: ClusterIP
