apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/mongo-data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath

  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
data:
  zabbix_agentd.conf: |
    Server=0.0.0.0/0
    ServerActive=zabbix-zabbix-server
    Hostname=mongo-container
    ListenPort=10050
    ListenIP=0.0.0.0
    LogType=console

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "user"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "pass"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-6.0-latest
          volumeMounts:
            - name: zabbix-agent-config
              mountPath: /etc/zabbix/zabbix_agentd.conf
              subPath: zabbix_agentd.conf
          ports:
            - containerPort: 10050
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: zabbix-agent-config
          configMap:
            name: zabbix-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31115
  selector:
    app: mongodb


---
apiVersion: v1
kind: Service
metadata:
  name: mongo-zabbix-agent-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 10050
    targetPort: 10050
  type: ClusterIP