apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-config
data:
  ACCEPT_EULA: "Y"
  SA_PASSWORD: "YourStrong!Password"
  MSSQL_PID: "Express"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/sqlserver-data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
spec:
  volumeName: sqlserver-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
data:
  zabbix_agentd.conf: |
    Server=0.0.0.0/0
    ServerActive=zabbix-zabbix-server
    Hostname=sqlserver-container
    ListenPort=10050
    ListenIP=0.0.0.0
    LogType=console


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 10001:10001 /var/opt/mssql"]
        volumeMounts:
          - name: mssql-data
            mountPath: /var/opt/mssql

      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        envFrom:
        - configMapRef:
            name: sqlserver-config
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql/data
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 10
          periodSeconds: 5
      
      - name: zabbix-agent
        image: zabbix/zabbix-agent:alpine-6.0-latest
        volumeMounts:
        - name: zabbix-agent-config
          mountPath: /etc/zabbix/zabbix_agentd.conf
          subPath: zabbix_agentd.conf
        ports:
        - containerPort: 10050


      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: sqlserver-pvc
      - name: zabbix-agent-config
        configMap:
          name: zabbix-agent-config
---

apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31111
  type: NodePort


---

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent-service
spec:
  selector:
    app: sqlserver
  ports:
  - protocol: TCP
    port: 10050
    targetPort: 10050
  type: ClusterIP
